/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author devfo
 */
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        jtfID = new javax.swing.JTextField();
        btnCheckID = new javax.swing.JButton();
        lblPw = new javax.swing.JLabel();
        jtfIPw = new javax.swing.JTextField();
        lblCheckPw = new javax.swing.JLabel();
        jtfICheckPw = new javax.swing.JTextField();
        jtfName = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        lblMember = new javax.swing.JLabel();
        lblHobby = new javax.swing.JLabel();
        rbnMember = new javax.swing.JRadioButton();
        rbnHMember = new javax.swing.JRadioButton();
        rbnStudent = new javax.swing.JRadioButton();
        chkSwim = new javax.swing.JCheckBox();
        chkGame = new javax.swing.JCheckBox();
        chkGolf = new javax.swing.JCheckBox();
        chkBook = new javax.swing.JCheckBox();
        chkTennis = new javax.swing.JCheckBox();
        chkSki = new javax.swing.JCheckBox();
        lblJob = new javax.swing.JLabel();
        cbxJob = new javax.swing.JComboBox<>();
        lblPayfor = new javax.swing.JLabel();
        sclPayfor = new javax.swing.JScrollPane();
        lsPayfor = new javax.swing.JList<>();
        btnSubmit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setText("회원가입");

        lblID.setText("아이디");

        jtfID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfIDActionPerformed(evt);
            }
        });

        btnCheckID.setText("중복확인");

        lblPw.setText("비밀번호");

        lblCheckPw.setText("비밀번호 확인");

        jtfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNameActionPerformed(evt);
            }
        });

        lblName.setText("이름");

        lblMember.setText("회원 구분");

        lblHobby.setText("관심 분야");

        rbnMember.setText("정회원");
        rbnMember.setActionCommand("Member");

        rbnHMember.setText("준회원");
        rbnHMember.setActionCommand("Member");

        rbnStudent.setText("학생회원");
        rbnStudent.setActionCommand("Member");

        chkSwim.setText("수영");
        chkSwim.setActionCommand("Hobby");

        chkGame.setText("게임");
        chkGame.setActionCommand("Hobby");

        chkGolf.setText("골프");
        chkGolf.setActionCommand("Hobby");

        chkBook.setText("독서");
        chkBook.setActionCommand("Hobby");

        chkTennis.setText("테니스");
        chkTennis.setActionCommand("Hobby");

        chkSki.setText("스키");
        chkSki.setActionCommand("Hobby");

        lblJob.setText("직업");

        cbxJob.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "회사원", "학생", "교수", "엔지니어" }));

        lblPayfor.setText("결제 방법");

        lsPayfor.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "현금", "카드", "포인트" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        sclPayfor.setViewportView(lsPayfor);

        btnSubmit.setText("회원 가입");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSubmit)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCheckPw)
                                    .addComponent(lblPw)
                                    .addComponent(lblID)
                                    .addComponent(lblName)
                                    .addComponent(lblMember)
                                    .addComponent(lblHobby)
                                    .addComponent(lblJob)
                                    .addComponent(lblPayfor))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(chkSwim)
                                        .addGap(18, 18, 18)
                                        .addComponent(chkGame)
                                        .addGap(18, 18, 18)
                                        .addComponent(chkGolf))
                                    .addComponent(jtfName, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfIPw, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jtfID, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnCheckID))
                                    .addComponent(jtfICheckPw, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rbnMember)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbnHMember)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbnStudent))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(chkSki)
                                        .addGap(18, 18, 18)
                                        .addComponent(chkBook)
                                        .addGap(18, 18, 18)
                                        .addComponent(chkTennis))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(sclPayfor, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cbxJob, javax.swing.GroupLayout.Alignment.LEADING, 0, 176, Short.MAX_VALUE)))))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID)
                    .addComponent(jtfID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCheckID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPw)
                    .addComponent(jtfIPw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCheckPw)
                    .addComponent(jtfICheckPw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(jtfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMember)
                    .addComponent(rbnMember)
                    .addComponent(rbnHMember)
                    .addComponent(rbnStudent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHobby)
                    .addComponent(chkSwim)
                    .addComponent(chkGame)
                    .addComponent(chkGolf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkSki)
                    .addComponent(chkBook)
                    .addComponent(chkTennis))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJob)
                    .addComponent(cbxJob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPayfor)
                    .addComponent(sclPayfor, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(btnSubmit)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfIDActionPerformed

    private void jtfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckID;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> cbxJob;
    private javax.swing.JCheckBox chkBook;
    private javax.swing.JCheckBox chkGame;
    private javax.swing.JCheckBox chkGolf;
    private javax.swing.JCheckBox chkSki;
    private javax.swing.JCheckBox chkSwim;
    private javax.swing.JCheckBox chkTennis;
    private javax.swing.JTextField jtfICheckPw;
    private javax.swing.JTextField jtfID;
    private javax.swing.JTextField jtfIPw;
    private javax.swing.JTextField jtfName;
    private javax.swing.JLabel lblCheckPw;
    private javax.swing.JLabel lblHobby;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblJob;
    private javax.swing.JLabel lblMember;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPayfor;
    private javax.swing.JLabel lblPw;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JList<String> lsPayfor;
    private javax.swing.JRadioButton rbnHMember;
    private javax.swing.JRadioButton rbnMember;
    private javax.swing.JRadioButton rbnStudent;
    private javax.swing.JScrollPane sclPayfor;
    // End of variables declaration//GEN-END:variables
}
