/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author devfo
 */
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mnuFIle_Open = new javax.swing.JMenuItem();
        mnuFIle_Save = new javax.swing.JMenuItem();
        mnuFIle_Exit = new javax.swing.JMenuItem();
        mnuEdit = new javax.swing.JMenu();
        mnuGraphic = new javax.swing.JMenu();
        mnuGraphic_Line = new javax.swing.JMenuItem();
        mnuGraphic_Eclipse = new javax.swing.JMenuItem();
        mnuGraphic_Rectangle = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnuFile.setText("File");
        mnuFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFileActionPerformed(evt);
            }
        });

        mnuFIle_Open.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnuFIle_Open.setText("Open");
        mnuFIle_Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFIle_OpenActionPerformed(evt);
            }
        });
        mnuFIle_Open.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mnuFIle_OpenKeyPressed(evt);
            }
        });
        mnuFile.add(mnuFIle_Open);

        mnuFIle_Save.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnuFIle_Save.setText("Save");
        mnuFIle_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFIle_SaveActionPerformed(evt);
            }
        });
        mnuFIle_Save.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mnuFIle_SaveKeyPressed(evt);
            }
        });
        mnuFile.add(mnuFIle_Save);

        mnuFIle_Exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnuFIle_Exit.setText("Exit");
        mnuFIle_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFIle_ExitActionPerformed(evt);
            }
        });
        mnuFIle_Exit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mnuFIle_ExitKeyPressed(evt);
            }
        });
        mnuFile.add(mnuFIle_Exit);

        jMenuBar1.add(mnuFile);

        mnuEdit.setText("Edit");
        jMenuBar1.add(mnuEdit);

        mnuGraphic.setText("Graphic");

        mnuGraphic_Line.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnuGraphic_Line.setText("jMenuItem1");
        mnuGraphic_Line.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                mnuGraphic_LineMenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        mnuGraphic_Line.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuGraphic_LineActionPerformed(evt);
            }
        });
        mnuGraphic.add(mnuGraphic_Line);

        mnuGraphic_Eclipse.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnuGraphic_Eclipse.setText("jMenuItem2");
        mnuGraphic_Eclipse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuGraphic_EclipseActionPerformed(evt);
            }
        });
        mnuGraphic_Eclipse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mnuGraphic_EclipseKeyPressed(evt);
            }
        });
        mnuGraphic.add(mnuGraphic_Eclipse);

        mnuGraphic_Rectangle.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnuGraphic_Rectangle.setText("jMenuItem3");
        mnuGraphic_Rectangle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuGraphic_RectangleActionPerformed(evt);
            }
        });
        mnuGraphic_Rectangle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mnuGraphic_RectangleKeyPressed(evt);
            }
        });
        mnuGraphic.add(mnuGraphic_Rectangle);

        jMenuBar1.add(mnuGraphic);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 588, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 347, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFileActionPerformed
        
    }//GEN-LAST:event_mnuFileActionPerformed

    private void mnuGraphic_LineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuGraphic_LineActionPerformed
        this.setTitle("Line Menu Click!");
    }//GEN-LAST:event_mnuGraphic_LineActionPerformed

    private void mnuGraphic_EclipseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuGraphic_EclipseActionPerformed
        this.setTitle("Eclipse Menu Click!");
    }//GEN-LAST:event_mnuGraphic_EclipseActionPerformed

    private void mnuGraphic_RectangleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuGraphic_RectangleActionPerformed
        this.setTitle("Rectangle Menu Click!");
    }//GEN-LAST:event_mnuGraphic_RectangleActionPerformed

    private void mnuGraphic_LineMenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_mnuGraphic_LineMenuKeyPressed
        this.setTitle("Line Menu Click!");
    }//GEN-LAST:event_mnuGraphic_LineMenuKeyPressed

    private void mnuGraphic_EclipseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mnuGraphic_EclipseKeyPressed
        this.setTitle("Eclipse Menu Click!");
    }//GEN-LAST:event_mnuGraphic_EclipseKeyPressed

    private void mnuGraphic_RectangleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mnuGraphic_RectangleKeyPressed
        this.setTitle("Rectangle Menu Click!");
    }//GEN-LAST:event_mnuGraphic_RectangleKeyPressed

    private void mnuFIle_OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFIle_OpenActionPerformed
        jFileChooser1.showOpenDialog(null);
    }//GEN-LAST:event_mnuFIle_OpenActionPerformed

    private void mnuFIle_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFIle_SaveActionPerformed
        jFileChooser1.showSaveDialog(null);
    }//GEN-LAST:event_mnuFIle_SaveActionPerformed

    private void mnuFIle_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFIle_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuFIle_ExitActionPerformed

    private void mnuFIle_OpenKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mnuFIle_OpenKeyPressed
        jFileChooser1.showOpenDialog(null);
    }//GEN-LAST:event_mnuFIle_OpenKeyPressed

    private void mnuFIle_SaveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mnuFIle_SaveKeyPressed
        jFileChooser1.showSaveDialog(null);
    }//GEN-LAST:event_mnuFIle_SaveKeyPressed

    private void mnuFIle_ExitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mnuFIle_ExitKeyPressed
        System.exit(0);
    }//GEN-LAST:event_mnuFIle_ExitKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnuEdit;
    private javax.swing.JMenuItem mnuFIle_Exit;
    private javax.swing.JMenuItem mnuFIle_Open;
    private javax.swing.JMenuItem mnuFIle_Save;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenu mnuGraphic;
    private javax.swing.JMenuItem mnuGraphic_Eclipse;
    private javax.swing.JMenuItem mnuGraphic_Line;
    private javax.swing.JMenuItem mnuGraphic_Rectangle;
    // End of variables declaration//GEN-END:variables
}
