/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author devfo
 */

import java.util.*;
import javax.swing.tree.*;

public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());
    DefaultTreeModel dftTreeModel = null;
    DefaultTreeSelectionModel dftTreeSelectionModel = new DefaultTreeSelectionModel();
    DefaultMutableTreeNode rootNode = new DefaultMutableTreeNode("Lecture Materials");
    DefaultMutableTreeNode comNode = new DefaultMutableTreeNode("Programming Language");
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        
        //SINGLE_SELECTION_MODE
        dftTreeSelectionModel.setSelectionMode(1);
        Vector<DefaultMutableTreeNode> myVC = new Vector<>();
        String[] objFolder = { "Java", "C#", "JSP" };
        
        for (int i = 0; i < objFolder.length; ++i) {
            myVC.add(new DefaultMutableTreeNode(objFolder[i]));
            comNode.add(myVC.get(i));
        }
        
        rootNode.add(comNode);
        dftTreeModel = new DefaultTreeModel(rootNode);
        jtrMainTree.setModel(dftTreeModel);
        jScrollPane1.getViewport().add(jtrMainTree, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtrMainTree = new javax.swing.JTree();
        lblTitle = new javax.swing.JLabel();
        btnInsert = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        lblPath = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtrMainTree.addTreeExpansionListener(new javax.swing.event.TreeExpansionListener() {
            public void treeCollapsed(javax.swing.event.TreeExpansionEvent evt) {
                jtrMainTreeTreeCollapsed(evt);
            }
            public void treeExpanded(javax.swing.event.TreeExpansionEvent evt) {
                jtrMainTreeTreeExpanded(evt);
            }
        });
        jtrMainTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jtrMainTreeValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jtrMainTree);

        lblTitle.setText("Tree Exam");

        btnInsert.setText("Insert");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        lblPath.setText("Path: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addGap(154, 154, 154))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnInsert)
                            .addComponent(btnDelete))
                        .addGap(0, 23, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPath)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitle)
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(btnInsert)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDelete)))
                .addGap(18, 18, 18)
                .addComponent(lblPath)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtrMainTreeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jtrMainTreeValueChanged
        DefaultMutableTreeNode node;
        
        node = (DefaultMutableTreeNode)jtrMainTree.getLastSelectedPathComponent();
        
        if (node == null) {
            return;
        }
        
        lblPath.setText("Path: " + node.getUserObject() + "(Selected)\n");
    }//GEN-LAST:event_jtrMainTreeValueChanged

    private void jtrMainTreeTreeCollapsed(javax.swing.event.TreeExpansionEvent evt) {//GEN-FIRST:event_jtrMainTreeTreeCollapsed
        lblPath.setText("Path: " + evt.getPath() + "(Selected)\n");
    }//GEN-LAST:event_jtrMainTreeTreeCollapsed

    private void jtrMainTreeTreeExpanded(javax.swing.event.TreeExpansionEvent evt) {//GEN-FIRST:event_jtrMainTreeTreeExpanded
        lblPath.setText("Path: " + evt.getPath() + "(Selected)\n");
    }//GEN-LAST:event_jtrMainTreeTreeExpanded

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        int index = 0;
        
        DefaultMutableTreeNode selectedNode;
        selectedNode = (DefaultMutableTreeNode)jtrMainTree.getLastSelectedPathComponent();
        
        if (selectedNode == null) {
            return;
        }
        
        DefaultMutableTreeNode newFolder = new DefaultMutableTreeNode("New Folder");
        index = selectedNode.getChildCount();
        dftTreeModel.insertNodeInto(newFolder, selectedNode, index);
        
        jtrMainTree.setModel(dftTreeModel);
        jtrMainTree.setSelectionModel(dftTreeSelectionModel);
        jScrollPane1.getViewport().add(jtrMainTree, null);
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        DefaultMutableTreeNode selectedNode;
        selectedNode = (DefaultMutableTreeNode)jtrMainTree.getLastSelectedPathComponent();
        
        if (selectedNode == null) {
            return;
        }
        
        dftTreeModel.removeNodeFromParent(selectedNode);
        
        jtrMainTree.setModel(dftTreeModel);
        jtrMainTree.setSelectionModel(dftTreeSelectionModel);
        jScrollPane1.getViewport().add(jtrMainTree, null);
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnInsert;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jtrMainTree;
    private javax.swing.JLabel lblPath;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
